# Text Based Sentiment Analysis

# IMPORTING NECESSARY MODULES

In [1]:
import numpy as np # For linear algebra
import pandas as pd # Data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt  # For Visualisation
%matplotlib inline
import seaborn as sns  # For Visualisation
from bs4 import BeautifulSoup  # For Text Parsing
from ydata_profiling import ProfileReport  # For generating data report

# IMPORTING DATASET

In [2]:
data = pd.read_csv('./train.csv')
data.head(15)

conversation_id  utterance_id   speaker  \
0      742555640001             0     agent   
1      742555640001             1  customer   
2      742555640001             2     agent   
3      742555640001             3  customer   
4      742555640001             4     agent   
5      742555640001             5     agent   
6      742555640001             6  customer   
7      742555640001             7     agent   
8      742555640001             8     agent   
9      742555640001             9  customer   
10     742555640001            10  customer   
11     742555640001            11     agent   
12     742555640001            12     agent   
13     742555640001            13     agent   
14     742555640001            14  customer   

                                                 text            saliency  
0                       May I know your name, please?                 NaN  
1          Uh yes, my name is {full_name:***** ****}.                 NaN  
2   , {first_name:*****}. How's your day going, {f...                 NaN  
3              It's going good. Thank you for asking.                 NaN  
4                That's great. So how can I help you?                 NaN  
5                                                mhm.                 NaN  
6   Uh yes, sir. I'm a new Raven member and I was ...  Reason for Contact  
7                                                mhm.                 NaN  
8                                           Yes, sir.                 NaN  
9   That has to be canceled by the 23rd. It had a ...  Reason for Contact  
10                                              Okay.                 NaN  
11  Okay, let okay, let me just assist you with th...                 NaN  
12       So are you referring for the Spiderman Pack.  Resolution Process  
13        , Superman, Spiderman and Raven Movie Pack.  Resolution Process  
14  I get I'm gonna get Superman anyway because I'...  Resolution Process

# DATA PREPROCESSING & VISUALISATION

In [3]:
data.isnull().sum()

conversation_id      0
utterance_id         0
speaker              0
text                 0
saliency           352
dtype: int64

In [ ]:
# data.shape

In [ ]:
# profile = ProfileReport(data, title="Pokemon Data Profiling Report")
# profile

In [4]:
def strip_html(text):
    soup = BeautifulSoup(text, "html.parser")
    return soup.get_text()
data['rich_text'] = data['text'].apply(strip_html)

# data=data.drop('Text',axis=1)
data

conversation_id  utterance_id   speaker  \
0       742555640001             0     agent   
1       742555640001             1  customer   
2       742555640001             2     agent   
3       742555640001             3  customer   
4       742555640001             4     agent   
..               ...           ...       ...   
774     742579770001           128  customer   
775     742579770001           129     agent   
776     742579770001           130     agent   
777     742579770001           131  customer   
778     742579770001           132       bot   

                                                  text saliency  \
0                        May I know your name, please?      NaN   
1           Uh yes, my name is {full_name:***** ****}.      NaN   
2    , {first_name:*****}. How's your day going, {f...      NaN   
3               It's going good. Thank you for asking.      NaN   
4                 That's great. So how can I help you?      NaN   
..                                                 ...      ...   
774                                                 I.      NaN   
775                                               mhm.      NaN   
776                                                 A.      NaN   
777                                             Ma'am?      NaN   
778                             issue auto wrapped up.      NaN   

                                             rich_text  
0                        May I know your name, please?  
1           Uh yes, my name is {full_name:***** ****}.  
2    , {first_name:*****}. How's your day going, {f...  
3               It's going good. Thank you for asking.  
4                 That's great. So how can I help you?  
..                                                 ...  
774                                                 I.  
775                                               mhm.  
776                                                 A.  
777                                             Ma'am?  
778                             issue auto wrapped up.  

[779 rows x 6 columns]

In [5]:
# data['saliency'] = data['saliency'].apply(lambda x: 0 if x != NaN else 1)
data['saliency'] = np.where(data['saliency'].str.isnumeric(), 0, 1)

In [6]:
data['saliency'].describe()

count    779.000000
mean       0.548139
std        0.497997
min        0.000000
25%        0.000000
50%        1.000000
75%        1.000000
max        1.000000
Name: saliency, dtype: float64

In [7]:
cnt1, cnt2 = 0, 0
for i in data['saliency']:
    if i == 1:
        cnt1 += 1
    else:
        cnt2 += 1
print(cnt1, cnt2)

427 352


In [19]:
data.to_csv('train-cleaned.csv')

# MODEL BUILDING

In [2]:
import numpy as np # For linear algebra
import pandas as pd # Data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt  # For Visualisation
%matplotlib inline
import seaborn as sns  # For Visualisation
from bs4 import BeautifulSoup  # For Text Parsing
from ydata_profiling import ProfileReport  # For generating data report

In [3]:
data = pd.read_csv('train-cleaned.csv')
data

Unnamed: 0.1  Unnamed: 0  conversation_id  utterance_id   speaker  \
0               0           0     742555640001             0     agent   
1               1           1     742555640001             1  customer   
2               2           2     742555640001             2     agent   
3               3           3     742555640001             3  customer   
4               4           4     742555640001             4     agent   
..            ...         ...              ...           ...       ...   
774           774         774     742579770001           128  customer   
775           775         775     742579770001           129     agent   
776           776         776     742579770001           130     agent   
777           777         777     742579770001           131  customer   
778           778         778     742579770001           132       bot   

                                                  text  saliency  \
0                        May I know your name, please?         0   
1           Uh yes, my name is {full_name:***** ****}.         0   
2    , {first_name:*****}. How's your day going, {f...         0   
3               It's going good. Thank you for asking.         0   
4                 That's great. So how can I help you?         0   
..                                                 ...       ...   
774                                                 I.         0   
775                                               mhm.         0   
776                                                 A.         0   
777                                             Ma'am?         0   
778                             issue auto wrapped up.         0   

                                             rich_text  \
0                           May I know name , please ?   
1    Uh yes , name { full_name : * * * * * * * * * } .   
2    , { first_name : * * * * * } . How 's day goin...   
3                    It 's going good . Thank asking .   
4                          That 's great . So I help ?   
..                                                 ...   
774                                                I .   
775                                              mhm .   
776                                                A .   
777                                            Ma'am ?   
778                               issue auto wrapped .   

                               Extracted text  
0                 May I know your name please  
1                 Uh yes my name is fullname   
2     firstname Hows your day going firstname  
3         Its going good Thank you for asking  
4           Thats great So how can I help you  
..                                        ...  
774                                         I  
775                                       mhm  
776                                         A  
777                                      Maam  
778                     issue auto wrapped up  

[779 rows x 9 columns]

In [4]:
import nltk  #Natural Language Processing Toolkit
def punc_clean(text):
    import string as st
    a=[w for w in text if w not in st.punctuation]
    return ''.join(a)
data[''] = data['Extracted text'].apply(punc_clean)
#data.head(2)

In [5]:
def remove_stopword(text):
    stopword=nltk.corpus.stopwords.words('english')
    stopword.remove('not')
    a=[w for w in nltk.word_tokenize(text) if w not in stopword]
    return ' '.join(a)
data['Extracted text'] = data['Extracted text'].apply(remove_stopword)

In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectr = TfidfVectorizer(ngram_range=(1,2),min_df=1)
vectr.fit(data['Extracted text'])

vect_X = vectr.transform(data['Extracted text'])

In [7]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

clf=model.fit(vect_X,data['saliency'])
# clf.score(vect_X, data['saliency'])*100

# PREDICTION

In [8]:
clf.predict(vectr.transform(['''UThat has to be canceled by the 23rd. It had a reminder on my my television uh so I wanted to make sure. Yeah, I wanted to go ahead and cancel that today promo all the free promo channels are. However, you say that.''']))

array([1])

In [12]:
clf.predict(vectr.transform(['''uhhh....''']))

array([1])

In [15]:
clf.predict(vectr.transform(['''mhm . Let check happening .''']))

array([1])

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=4d282b10-3250-4323-8e4d-a3cd11fe8ba3' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>